site_name: Chips
site_author: PickingChip
site_description: PickingChip's Chips
site_url: https://pickingchip.github.io/
repo_url: https://github.com/PickingChip/PickingChip.github.io
repo_name: GitHub
docs_dir: docs

nav:
  - Home: "index.md"
  - About: About.md
  - 基础知识:
      PC硬件简介: "./基础知识/1.电脑硬件配置简介.md"
      Windows系统: "./基础知识/2.Windows操作简介.md"
      从终端开始的系统结构探秘: "./基础知识/3.从终端开始的系统结构探秘.md"
      编程世界里的尚方宝剑IDE: "./基础知识/4.编程世界里的尚方宝剑.md"

  - 团队开发:
      Git: "./团队开发/Git.md"
      GitHub: "./团队开发/GitHub.md"
      Markdown: "./团队开发/Markdown.md"

  - 嵌入式:
      Stm32:
        Stm32概述: "./嵌入式/Stm32/Stm32概述.md"
        重要外设: "./嵌入式/Stm32/重要外设.md"
        通信协议: "./嵌入式/Stm32/通信协议.md"
        启动过程: "./嵌入式/Stm32/启动过程.md"
      工具链:
        编译器: "./嵌入式/工具链/编译器.md"
        调试器: "./嵌入式/工具链/调试器.md"
        构建工具: "./嵌入式/工具链/构建工具.md"
        编辑器: "./嵌入式/工具链/编辑器.md"
      树莓派: "./嵌入式/树莓派.md"

  - 操作系统:
      Linux: "./操作系统/Linux.md"
      FreeRTOS: "./操作系统/FreeRTOS.md"
      bash_shell: "./操作系统/bash_shell.md"

  - 计算机组成:
      1.计算机基本结构: "./计算机组成/计算机基本结构.md"
      2.指令集系统结构: "./计算机组成/指令集系统结构.md"
      3.输入输出结构: "./计算机组成/输入输出结构.md"
      4.重要的软件部分: "./计算机组成/软件.md"
      5.存储器系统: "./计算机组成/存储器系统.md"

  - 计算机网络:
      计算机网络: "./计算机网络/计算机网络.md"

  - 计算机语言:
      C+: "./计算机语言/C+.md"
      C库函数: "./计算机语言/C库函数.md"
      C++: "./计算机语言/C++.md"
      Qt: "./计算机语言/QT.md"
      # Python: "./计算机语言/Python.md"

  # - 数学类:
  #     数模:
  #       第一讲:距离优略分析法: "./数学类/数模/第一讲:距离优略分析法.md"
  #     Matlab语法: "./数学类/Matlab语法.md"
  #     Matlab仿真: "./数学类/Matlab仿真.md"

theme:
  name: material
  palette:
    # 亮色主题
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: teal
      toggle:
        icon: material/brightness-7
        name: 切换至暗色模式

    # 暗色主题
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: 切换至亮色模式
  loge: "images/electric_bolt.png"
  favicon: "images/catching_pokem.png"

  logo: "images/catching_pokem.png"
# 可用的主题色：
# red, pink, purple, deep purple, indigo, blue, light blue,
# cyan, teal, green, light green, lime, yellow, amber,
# orange, deep orange, brown, grey, blue grey
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - admonition #MkDocs 警告框
  - footnotes #脚注
  - meta #自定义文章元数据
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - mdx_truly_sane_lists
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
